# Generated by Django 5.2.12 on 2026-04-01 12:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivicBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. GDA, MCD, NMMC', max_length=200)),
                ('region_boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, help_text="Spatial boundary of the civic body's jurisdiction", null=True, srid=4326)),
                ('contact_email', models.EmailField(max_length=254)),
                ('webhook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Civic Bodies',
            },
        ),
    ]
